# Generated by Django 6.0.7 on 2026-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='important_notice',
            field=models.TextField(blank=True, verbose_name='نکات مهم'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه برای انتخاب دسته'),
        ),
        migrations.AddField(
            model_name='category',
            name='usage_guide',
            field=models.TextField(blank=True, verbose_name='راهنمای استفاده از این دسته'),
        ),
        migrations.AddField(
            model_name='category',
            name='writing_help',
            field=models.TextField(blank=True, verbose_name='راهنمای نوشتن مطلب'),
        ),
    ]
