# Generated by Django 6.0 on 2026-06-30 11:32

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[accounts.models.validate_image_size], verbose_name='عکس پروفایل')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='نام مستعار (اختیاری)')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='درباره من')),
                ('child_age', models.IntegerField(blank=True, null=True, verbose_name='سن فرزند')),
                ('condition_type', models.CharField(blank=True, max_length=100, verbose_name='نوع معلولیت/شرایط فرزند')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='شهر محل سکونت')),
                ('show_bio', models.BooleanField(default=True, verbose_name='نمایش درباره من')),
                ('show_child_age', models.BooleanField(default=True, verbose_name='نمایش سن فرزند')),
                ('show_condition_type', models.BooleanField(default=True, verbose_name='نمایش نوع شرایط')),
                ('show_location', models.BooleanField(default=True, verbose_name='نمایش شهر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500, verbose_name='علت گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='کاربر گزارش شده')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='گزارش دهنده')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
