# Generated by Django 5.1.7 on 2026-07-09 06:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل\u200cهای کاربران'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'گزارش', 'verbose_name_plural': 'گزارش\u200cها'},
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='child_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='سن فرزند (سال)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='condition_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع معلولیت / شرایط فرزند'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام مستعار'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_bio',
            field=models.BooleanField(default=True, verbose_name="نمایش 'درباره من' به دیگران"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ گزارش'),
        ),
    ]
