# Generated by Django 6.0.7 on 2026-08-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='membership_status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('verified', 'عضو تأیید شده'), ('blocked', 'مسدود شده')], default='pending', max_length=20, verbose_name='وضعیت عضویت'),
        ),
    ]
