# Generated by Django 6.0.7 on 2026-08-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relationship_to_child',
            field=models.CharField(blank=True, max_length=50, verbose_name='نسبت با کودک'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_note',
            field=models.TextField(blank=True, max_length=500, verbose_name='توضیح برای مدیر'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_requested',
            field=models.BooleanField(default=False, verbose_name='درخواست بررسی عضویت'),
        ),
    ]
